server:
  port: 3000
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/example_db
    username: tobi
    password: tobi4ever
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect